CREATE DATABASE QLKhachSan
--------------------------------------
USE QLKhachSan
------------ Create Table ------------
CREATE TABLE KhachHang (
   MaKH INT IDENTITY(1,1) PRIMARY KEY,
   HoTen NVARCHAR(100) NOT NULL,
   DiaChi NVARCHAR(200) NOT NULL,
   GioiTinh NVARCHAR(10) NOT NULL,
   Sdt NVARCHAR(20) NOT NULL,
   CMND NVARCHAR(20) UNIQUE NOT NULL 
);

CREATE TABLE Phong (
   MaPhong INT IDENTITY(1,1) PRIMARY KEY,
   TenPhong NVARCHAR(50) NOT NULL ,
   LoaiPhong NVARCHAR(50) NOT NULL,
   GiaPhong FLOAT NOT NULL,
   TrangThai NVARCHAR(20) NOT NULL
);

CREATE TABLE NhanVien (
   MaNV INT IDENTITY(1,1) PRIMARY KEY,
   HoTen NVARCHAR(100) NOT NULL,
   Sdt NVARCHAR(20) NOT NULL
);

CREATE TABLE ChiTietDatPhong (
   MaDatPhong INT IDENTITY(1,1) PRIMARY KEY,
   MaPhong INT NOT NULL,
   MaKH INT NOT NULL,
   NgayThue DATE NOT NULL,
   NgayTra DATE NOT NULL,
   SoNguoi INT NOT NULL,
   DaThanhToan BIT NOT NULL DEFAULT 0,
   MaNV INT NOT NULL,
   CONSTRAINT FK_ChiTietDatPhong_MaPhong FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
   CONSTRAINT FK_ChiTietDatPhong_MaKH FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
   CONSTRAINT FK_ChiTietDatPhong_MaNV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

CREATE TABLE DichVu (
   MaDichVu INT IDENTITY(1,1) PRIMARY KEY,
   TenDichVu NVARCHAR(50) NOT NULL,
   GiaDichVu FLOAT NOT NULL
);

CREATE TABLE DatPhongDichVu (
   MaDatPhong INT NOT NULL,
   MaDichVu INT NOT NULL,
   SoLuong INT NOT NULL,
   CONSTRAINT PK_DatPhongDichVu PRIMARY KEY (MaDatPhong, MaDichVu),
   CONSTRAINT FK_DatPhongDichVu_MaDatPhong FOREIGN KEY (MaDatPhong) REFERENCES ChiTietDatPhong(MaDatPhong),
   CONSTRAINT FK_DatPhongDichVu_MaDichVu FOREIGN KEY (MaDichVu) REFERENCES DichVu(MaDichVu)
);

CREATE TABLE HoaDon (
   MaHoaDon INT IDENTITY(1,1) PRIMARY KEY,
   MaDatPhong INT NOT NULL,
   TongTien FLOAT NOT NULL,
   NgayIn DATE NOT NULL,
   CONSTRAINT FK_HoaDon_MaDatPhong FOREIGN KEY (MaDatPhong) REFERENCES ChiTietDatPhong(MaDatPhong)
);

CREATE TABLE Account (
   Id INT IDENTITY(1,1) PRIMARY KEY,
   Username VARCHAR(50) UNIQUE NOT NULL,
   Pass VARCHAR(255) NOT NULL,
   MaKH INT,
   MaNV INT,
   CONSTRAINT FK_Account_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
   CONSTRAINT FK_Account_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);


--------Insert-----------

s